//! Support for the code generated by the `qi` attribute macros.
//!
//! Nothing in this module is public API: it may change without notice.

use crate::{
    error::ValueConversionError,
    object::{params, ActionNameOrId, MetaObject},
    value::{FromValue, IntoValue, Reflect, Signature, Type, Value},
    Error, Result,
};

/// The type of the parameters tuple of a member whose values have the given static type.
pub fn params_type_of(ty: Option<Type>) -> Type {
    params::params_type_of(ty)
}

/// Decodes the arguments of a call into the parameters type `A`, converting them to the declared
/// parameters signature first.
pub fn decode_args<A>(params_signature: &Signature, args: Value<'_>) -> Result<A>
where
    A: FromValue<'static> + Reflect,
{
    let args = args
        .convert_to(params_signature.as_type())
        .map_err(ValueConversionError::Arguments)?;
    A::from_value(params::from_params::<A>(args).into_owned())
        .map_err(|err| ValueConversionError::Arguments(err).into())
}

/// Encodes the return value of a method.
pub fn encode_return<R>(value: R) -> Value<'static>
where
    R: IntoValue<'static>,
{
    value.into_value()
}

/// Checks that an object exposes every member of an interface, by name.
pub fn check_interface(object: &MetaObject, interface: &MetaObject) -> Result<()> {
    for method in interface.methods.values() {
        let ident = ActionNameOrId::Name(method.name.clone());
        if object.method(&ident).is_none() {
            return Err(Error::MethodNotFound(ident));
        }
    }
    for signal in interface.signals.values() {
        let ident = ActionNameOrId::Name(signal.name.clone());
        if object.signal(&ident).is_none() && object.property(&ident).is_none() {
            return Err(Error::SignalNotFound(ident));
        }
    }
    for property in interface.properties.values() {
        let ident = ActionNameOrId::Name(property.name.clone());
        if object.property(&ident).is_none() {
            return Err(Error::PropertyNotFound(ident));
        }
    }
    Ok(())
}
