[package]
name = "tests-macros"

edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
rust-version.workspace = true

publish = false

[dependencies]
qi = { package = "libqi-vibe", path = "../qi" }
qi-macros = { package = "libqi-macros-vibe", path = "../qi-macros" }
trybuild = "1.0.111"
assert_matches = "1.5.0"
syn = { version = "2.0.110", features = ["extra-traits"] }
pretty_assertions = "1.4.1"
